name: app_environment
channels:
  - snowflake
dependencies:
  - numpy=1.26.4
  - pandas=2.2.2
  - python=3.11.*
  - requests=2.32.5
  - scikit-learn=1.4.2
  - snowflake-snowpark-python=
  - streamlit=
